import React, { useState } from 'react';
import { User } from '../../types';
import Modal from '../common/Modal';
import { InfoIcon, GalleryIcon, StarIcon, BellOffIcon } from '../icons/Icons';

interface MetaAIProfileProps {
    user: User | null;
    isOpen: boolean;
    onClose: () => void;
}

const MetaAILogo: React.FC<{className?: string}> = ({className}) => (
    <div className={`w-24 h-24 p-1 rounded-full bg-gradient-to-br from-blue-400 via-purple-500 to-cyan-400 ${className}`}>
        <div className="w-full h-full bg-white dark:bg-slate-800 rounded-full p-2">
            <div className="w-full h-full rounded-full bg-gradient-to-br from-blue-400 via-purple-500 to-cyan-400" />
        </div>
    </div>
)

const Toggle: React.FC<{checked: boolean, onChange: (checked: boolean) => void}> = ({ checked, onChange }) => (
    <label className="relative inline-flex items-center cursor-pointer">
        <input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="sr-only peer" />
        <div className="w-11 h-6 bg-slate-200 dark:bg-slate-600 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-slate-600 peer-checked:bg-blue-500"></div>
    </label>
);


const MetaAIProfile: React.FC<MetaAIProfileProps> = ({ user, isOpen, onClose }) => {
    const [isMuted, setIsMuted] = useState(false);
    
    if (!user) return null;

    const ProfileListItem: React.FC<{icon: React.ReactNode, label: string, value?: string | number, action?: React.ReactNode}> = ({icon, label, value, action}) => (
        <div className="flex items-center w-full py-3">
            <div className="text-slate-500 dark:text-slate-400">{icon}</div>
            <span className="ml-4 font-medium text-slate-800 dark:text-slate-200 flex-1">{label}</span>
            {value !== undefined && <span className="text-slate-500 dark:text-slate-400 text-sm mr-4">{value}</span>}
            {action}
        </div>
    )

    return (
        <Modal isOpen={isOpen} onClose={onClose} title="">
            <div className="bg-white dark:bg-slate-800 -p-6">
                <div className="flex flex-col items-center pt-4 pb-6">
                    <MetaAILogo />
                    <h2 className="text-2xl font-bold mt-4 text-slate-900 dark:text-white">{user.name}</h2>
                    <p className="text-slate-500 dark:text-slate-400">with Llama 4</p>
                </div>

                <div className="space-y-2">
                    <div className="bg-slate-100 dark:bg-slate-700/50 rounded-lg px-4 py-3 flex items-center text-sm">
                        <p className="text-slate-600 dark:text-slate-300 flex-1">Messages are generated by AI from Meta.</p>
                        <InfoIcon className="w-5 h-5 text-slate-500 dark:text-slate-400" />
                    </div>

                    <div className="pt-4">
                        <h3 className="text-xs font-semibold uppercase text-slate-400 dark:text-slate-500 mb-1">About</h3>
                        <p className="text-slate-700 dark:text-slate-300">{user.about}</p>
                    </div>
                </div>

                <div className="mt-6 border-t border-slate-200 dark:border-slate-700 divide-y divide-slate-200 dark:divide-slate-700">
                    <ProfileListItem icon={<GalleryIcon className="w-6 h-6"/>} label="Media, links and docs" value={0} />
                    <ProfileListItem icon={<StarIcon className="w-6 h-6"/>} label="Starred messages" />
                    <ProfileListItem 
                        icon={<BellOffIcon className="w-6 h-6"/>} 
                        label="Mute notifications"
                        action={<Toggle checked={isMuted} onChange={setIsMuted} />}
                    />
                </div>
            </div>
        </Modal>
    );
};

export default MetaAIProfile;
